import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto flex h-screen items-center justify-center py-2">
        <h1 className="text-center text-3xl font-bold text-gray-900">
          Welcome to the basic template using{" "}
          <span className="rounded-md bg-gray-300 px-3 py-1 font-normal italic text-gray-700">
            Next.js
          </span>{" "}
          and{" "}
          <span className="rounded-md bg-gray-300 px-3 py-1 font-normal italic text-gray-700">
            Tailwindcss
          </span>
        </h1>
      </div>
    </div>
  );
}
